
services:
  dongguatv:
    build: .
    container_name: dongguatv
    restart: unless-stopped
    ports:
    - "8280:3000"
    environment:
    #- PORT=3000
    - TMDB_API_KEY=9512c4ab4c158993f6ca0eb8ea2b93f4
    - ADMIN_PASSWORD=lyfok
